# fly.toml app configuration file generated for backend-misty-sea-9571 on 2025-09-26T18:52:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monolitico'
primary_region = 'iad'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
