-- CreateTable
CREATE TABLE "InspeccionPesado" (
    "id" SERIAL NOT NULL,
    "marca_temporal" TIMESTAMP(3) NOT NULL,
    "nombre_inspector" TEXT NOT NULL,
    "contrato" TEXT NOT NULL,
    "campo_coordinacion" TEXT NOT NULL,
    "placa_vehiculo" TEXT NOT NULL,
    "kilometraje" INTEGER NOT NULL,
    "turno" TEXT NOT NULL,
    "altas_bajas" BOOLEAN NOT NULL,
    "direccionales" BOOLEAN NOT NULL,
    "parqueo" BOOLEAN NOT NULL,
    "freno" BOOLEAN NOT NULL,
    "reversa_alarma" BOOLEAN NOT NULL,
    "espejos" BOOLEAN NOT NULL,
    "vidrio_frontal" BOOLEAN NOT NULL,
    "presentacion_aseo" BOOLEAN NOT NULL,
    "pito" BOOLEAN NOT NULL,
    "gps" BOOLEAN NOT NULL,
    "cinturones" BOOLEAN NOT NULL,
    "puertas" BOOLEAN NOT NULL,
    "vidrios" BOOLEAN NOT NULL,
    "limpiaparabrisas" BOOLEAN NOT NULL,
    "extintor" BOOLEAN NOT NULL,
    "botiquin" BOOLEAN NOT NULL,
    "tapiceria" BOOLEAN NOT NULL,
    "indicadores" BOOLEAN NOT NULL,
    "objetos_sueltos" BOOLEAN NOT NULL,
    "frenos" BOOLEAN NOT NULL,
    "frenos_emergencia" BOOLEAN NOT NULL,
    "fugas_aire" BOOLEAN NOT NULL,
    "control_fugas_aire" BOOLEAN NOT NULL,
    "candados_bandas" BOOLEAN NOT NULL,
    "acoples_tomas" BOOLEAN NOT NULL,
    "nivel_aceite_motor" BOOLEAN NOT NULL,
    "nivel_fluido_frenos" BOOLEAN NOT NULL,
    "nivel_fluido_dir_hidraulica" BOOLEAN NOT NULL,
    "nivel_fluido_refrigerante" BOOLEAN NOT NULL,
    "nivel_fluido_limpia_parabrisas" BOOLEAN NOT NULL,
    "correas" BOOLEAN NOT NULL,
    "baterias" BOOLEAN NOT NULL,
    "llantas_labrado" BOOLEAN NOT NULL,
    "llantas_sin_cortes" BOOLEAN NOT NULL,
    "llanta_repuesto" BOOLEAN NOT NULL,
    "copas_pernos" BOOLEAN NOT NULL,
    "suspension" BOOLEAN NOT NULL,
    "direccion" BOOLEAN NOT NULL,
    "tapa_tanque" BOOLEAN NOT NULL,
    "equipo_carretera" BOOLEAN NOT NULL,
    "kit_ambiental" BOOLEAN NOT NULL,
    "documentacion" BOOLEAN NOT NULL,
    "observaciones" TEXT,
    "horas_sueno_suficientes" BOOLEAN NOT NULL,
    "libre_sintomas_fatiga" BOOLEAN NOT NULL,
    "condiciones_aptas" BOOLEAN NOT NULL,
    "consumo_medicamentos" BOOLEAN NOT NULL,
    "fecha" TIMESTAMP(3) NOT NULL,
    "nivel_riesgo" TEXT NOT NULL,
    "puntaje_total" INTEGER NOT NULL,
    "puntaje_fatiga" INTEGER NOT NULL,
    "tiene_alertas_criticas" BOOLEAN NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InspeccionPesado_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RechazoInspeccionPesado" (
    "id" SERIAL NOT NULL,
    "marca_temporal" TIMESTAMP(3),
    "nombre_inspector" TEXT,
    "contrato" TEXT,
    "campo_coordinacion" TEXT,
    "placa_vehiculo" TEXT,
    "kilometraje" INTEGER,
    "turno" TEXT,
    "altas_bajas" BOOLEAN,
    "direccionales" BOOLEAN,
    "parqueo" BOOLEAN,
    "freno" BOOLEAN,
    "reversa_alarma" BOOLEAN,
    "espejos" BOOLEAN,
    "vidrio_frontal" BOOLEAN,
    "presentacion_aseo" BOOLEAN,
    "pito" BOOLEAN,
    "gps" BOOLEAN,
    "cinturones" BOOLEAN,
    "puertas" BOOLEAN,
    "vidrios" BOOLEAN,
    "limpiaparabrisas" BOOLEAN,
    "extintor" BOOLEAN,
    "botiquin" BOOLEAN,
    "tapiceria" BOOLEAN,
    "indicadores" BOOLEAN,
    "objetos_sueltos" BOOLEAN,
    "frenos" BOOLEAN,
    "frenos_emergencia" BOOLEAN,
    "fugas_aire" BOOLEAN,
    "control_fugas_aire" BOOLEAN,
    "candados_bandas" BOOLEAN,
    "acoples_tomas" BOOLEAN,
    "nivel_aceite_motor" BOOLEAN,
    "nivel_fluido_frenos" BOOLEAN,
    "nivel_fluido_dir_hidraulica" BOOLEAN,
    "nivel_fluido_refrigerante" BOOLEAN,
    "nivel_fluido_limpia_parabrisas" BOOLEAN,
    "correas" BOOLEAN,
    "baterias" BOOLEAN,
    "llantas_labrado" BOOLEAN,
    "llantas_sin_cortes" BOOLEAN,
    "llanta_repuesto" BOOLEAN,
    "copas_pernos" BOOLEAN,
    "suspension" BOOLEAN,
    "direccion" BOOLEAN,
    "tapa_tanque" BOOLEAN,
    "equipo_carretera" BOOLEAN,
    "kit_ambiental" BOOLEAN,
    "documentacion" BOOLEAN,
    "observaciones" TEXT,
    "horas_sueno_suficientes" BOOLEAN,
    "libre_sintomas_fatiga" BOOLEAN,
    "condiciones_aptas" BOOLEAN,
    "consumo_medicamentos" BOOLEAN,
    "fecha" TIMESTAMP(3),
    "nivel_riesgo" TEXT,
    "puntaje_total" INTEGER,
    "puntaje_fatiga" INTEGER,
    "tiene_alertas_criticas" BOOLEAN,
    "motivo_rechazo" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RechazoInspeccionPesado_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "InspeccionPesado_placa_vehiculo_fecha_nombre_inspector_key" ON "InspeccionPesado"("placa_vehiculo", "fecha", "nombre_inspector");
