# fly.toml app configuration file generated for monolitico-cold-dew-3627 on 2025-09-29T07:21:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monolitico-cold-dew-3627'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
