-- CreateTable
CREATE TABLE "RechazoInspeccion" (
    "id" SERIAL NOT NULL,
    "fecha" TIMESTAMP(3),
    "marca_temporal" TIMESTAMP(3),
    "turno" TEXT,
    "conductor_nombre" TEXT,
    "placa_vehiculo" TEXT,
    "kilometraje" INTEGER,
    "contrato" TEXT,
    "campo_coordinacion" TEXT,
    "consumo_medicamentos" BOOLEAN,
    "horas_sueno_suficientes" BOOLEAN,
    "libre_sintomas_fatiga" BOOLEAN,
    "condiciones_aptas" BOOLEAN,
    "altas_bajas" BOOLEAN,
    "direccionales" BOOLEAN,
    "parqueo" BOOLEAN,
    "freno" BOOLEAN,
    "reversa" BOOLEAN,
    "espejos" BOOLEAN,
    "vidrio_frontal" BOOLEAN,
    "frenos" BOOLEAN,
    "frenos_emergencia" BOOLEAN,
    "cinturones" BOOLEAN,
    "puertas" BOOLEAN,
    "vidrios" BOOLEAN,
    "limpiaparabrisas" BOOLEAN,
    "observaciones" TEXT,
    "nivel_riesgo" TEXT,
    "puntaje_total" INTEGER,
    "puntaje_fatiga" INTEGER,
    "tiene_alertas_criticas" BOOLEAN,
    "motivo_rechazo" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RechazoInspeccion_pkey" PRIMARY KEY ("id")
);
